name: CI for ESP32 Project

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Run clang-format
      run: |
        sudo apt-get install -y clang-format
        clang-format -i hello_world/main/*.c
        git diff --exit-code
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.1
        target: esp32s3
        path: 'hello_world'
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: hello_world_build
        path: hello_world/build/hello_world.bin
        if-no-files-found: error
        compression-level: 0
